this system tracks 5 students across 3 subjects(out of 100)


             sub1     sub2       sub 3


student 1     78       85         90


student 2     45       60         55


student 3     88       92         95


student 4     30       40         35


student 5     65       70         75



create a 2d array

In [9]:
import numpy as np



In [10]:
marks = np.array([
    [78, 85, 90],   # Student 1
    [45, 60, 55],   # Student 2
    [88, 92, 95],   # Student 3
    [30, 40, 35],   # Student 4
    [65, 70, 75]    # Student 5
])

print(marks)



[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [11]:
print(np.shape(marks))  # Shape of the array
print(np.size(marks))   # Total number of elements
print(np.result_type(marks))  # Data type of the elements

#column and row numbering starts from 0
print(marks[1]) # Accessing the second row (Student 2's marks)
print(marks[0:,2])     # marks of all students in the third subject
print(marks[0, 1])#  marks of first student in second subject





(5, 3)
15
int64
[45 60 55]
[90 55 95 35 75]
85


In [12]:
print(np.mean(marks, axis=0))  # Average marks for each subject
avg = np.mean(marks, axis=1)  # Average marks for each student
result = np.where(marks >= 80, 1, 0)
print(result)


#global adjustments
print(marks+5) # Adding 5 marks to each student's score
print(marks) 



[61.2 69.4 70. ]
[[0 1 1]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [0 0 0]]
[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [13]:
mapping = np.where(marks > 50,1,0)
print(mapping)

data_cleaning = np.where(marks > 40,1,0)
print(data_cleaning)

[[1 1 1]
 [0 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [14]:
Grade_allocation = np.where(avg>=85,'A',np.where(avg>=70,'B',np.where(avg>=50,'C','No grade')))

# The above code is using nested np.where statements to allocate grades based on the average marks of each student.
# It checks if the average marks are greater than or equal to 85, then assigns 'A'. If not, it checks if the average marks are greater than or equal to 70,

print(Grade_allocation)


['B' 'C' 'A' 'No grade' 'B']


In [19]:
modified_marks = marks.copy()
print(marks_copy)
modified_marks = marks_copy + 5
print(marks_copy)
print(modified_marks)


#using copy fuction doesnot change original array


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]
