In [6]:
import numpy as np

In [8]:
arr=np.array([[1, 2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr.shape) #prints the shape of the array which is (2, 3) because it has 2 rows and 3 columns
# Output: (2, 3)
print(arr.dtype)  
# Output: int64 (or int32 depending on the system)
print(arr.ndim) #prints the number of dimensions of the array which is 2 because it is a 2D array  
# Output: 2
print(arr.size) #prints the total number of elements in the array which is 6 because there are 6 elements in the array (1, 2, 3, 4, 5, 6)  
# Output: 6

(2, 3)
int64
2
6


Typeconversion


In [ ]:
arr = np.array([1.5, 2.3, 3.1])
arr_int = arr.astype(int)
print(arr_int) 

[1 2 3]


indexing and slicing

In [13]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr[0])
print(arr[-1])

10
100


1D Slicing

In [ ]:
print(arr[1:3]) #prints the elements from index 1 to index 2 (not including index 3) which are 20 and 30
print(arr[:2]) #prints the elements from the beginning of the array to index 1 (not including index 2) which are 10 and 20
print(arr[::3])#prints every 3rd element of the array starting from index 0 which are 10 and 40
print(arr[::-3]) #prints the elements of the array in reverse order

[20 30]
[10 20]
[ 10  40  70 100]
[100  70  40  10]


2D Indexing

In [21]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
print(mat[0,1]) 
#indexing of row or column and also element starts from 0
print(mat[1,0])
print(mat[1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
4
[4 5 6]


slicing 

In [22]:
print(mat[:,2]) #prints the 3rd column of the matrix which are 3, 6, and 9
print(mat[1,:]) #prints the 2nd row of the matrix which are 4, 5, and 6

[3 6 9]
[4 5 6]


In [23]:
a = np.array([1, 2, 3])
b = np.copy(a)
b[0]= 99
print(a)
print(b)



[1 2 3]
[99  2  3]


In [24]:
b = a
b[0] = 99
print(a)
print(b) # here overwriting in a occured so we use copy method instead b=a way

[99  2  3]
[99  2  3]


Basic Array Operations(Vector Power)

In [ ]:
a = np.array([[1,2,3]])
b= np.array([[4,5,6]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[5 7 9]]
[[-3 -3 -3]]
[[ 4 10 18]]
[[0.25 0.4  0.5 ]]


Scalar operations

In [ ]:
print(a+10)
print(a*2)


[[11 12 13]]
[[2 4 6]]


Universal functions

In [25]:
print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))
print(np.sin(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a)) # standard deviation
print(np.var(a)) # variance

[9.94987437 1.41421356 1.73205081]
[4.59511985 0.69314718 1.09861229]
[9.88903032e+42 7.38905610e+00 2.00855369e+01]
[-0.99920683  0.90929743  0.14112001]
2
99
104
34.666666666666664
3.0
45.492368102304326
2069.555555555556


Boolean indexing

In [27]:
arr = np.array([10,20,30,40,50])
print(arr[arr >= 20])  # Boolean indexing



[20 30 40 50]


Broadcasting rule: doing elementary operations on arrays or any other data types
or
we try to expand rows or columns in a array matrix to match the shape of the array

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr + 10)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))  # normal Matrix multiplication
print(a.T)        # Transpose of a

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
np.random.randn(5)



array([ 1.56696901, -0.56099973, -1.39094169, -0.11224903,  0.78485487])

In [ ]:
np.random.randn(3,3)



array([[ 1.03986165, -1.66734173,  0.56327624],
       [-1.49701217, -1.28846266, -1.01694617],
       [ 0.58429415, -1.43333315, -0.25947518]])

In [ ]:
np.random.randint(1, 100, 10) # generates 10 random integers between 1 and 100


array([35, 70, 14, 72, 12, 79, 95, 70, 95, 85], dtype=int32)

Reshaping Arrays

In [37]:
arr = np.arange(12).reshape(3,4) # arange starts from 0 and goes up to 11 (not including 12) with a step of 1
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


you need to track sales of 3 products(headphones,watches,speakers) over 4 days(monday,tuesday,wednesday,thursday)
row 0 headphones
row 1 smartphones
row 2 speakers

on 05/02/26 


In [ ]:
arr10 = np.array([[1,2,3],[4,5,6]])
print(arr)
print(np.sum(arr10))  # Total sum
#axis is used to specify the dimension along which the operation is performed
print(np.sum(arr10, axis=0))  # Sum along columns
print(np.sum(arr10, axis=1))  # Sum along rows



[ 0  1  2  3  4  5  6  7  8  9 10 11]
21
[5 7 9]
[ 6 15]


where in numpy (just like if-else)

In [31]:
arr = np.array([10,-5,90,-3,15])

result = np.where(arr < 0, 0 , arr)
 # here we say if arr is < zero then replace with zero or just print same arr[element]
 #if element is < 0 we write 0 else we write element itself
print(result)


result = np.where(arr % 2 != 0, -1,  arr)
# if element is odd we replace with -1 else element itself
print(result)

#if student scores > 50 then passed or not so do it and pass means 1 and fail means 0

result = np.where(arr >= 50, 1, 0)
print(result)




[10  0 90  0 15]
[10 -1 90 -1 -1]
[0 0 1 0 0]


In [ ]:
data = np.array([10, 20, 30, 30, 30])
mean_val = np.mean(data)

result = np.where(data > mean_val, mean_val, data) # if element is greater than mean_val we replace with mean_val else element itself
print(result)
print(result.dtype) #why result is of type int64 because the original data array is of type int64 and the mean_val is also of type int64, so the result of the np.where function will also be of type int64.

[10. 20. 24. 24. 24.]
float64


In [ ]:
mat = np.array([[10,60,30],[80,70,90]])

result = np.where(mat >= 50, 1,0)

print(result)

[[0 1 0]
 [1 1 1]]
