In [2]:
import numpy as np

you need to track sales of 3 products(headphones,watches,speakers) over 4 days(monday,tuesday,wednesday,thursday)
row 0 headphones
row 1 smartphones
row 2 speakers

In [ ]:
cost_price = np.array([1500,3000,5000,0])

daily_sales = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

print(np.shape(cost_price)) #prints the shape of the cost_price array which is (4,) because it is a 1-dimensional array with 4 elements
print(np.shape(daily_sales)) #prints the shape of the daily_sales array which is (3, 4) because it is a 2-dimensional array with 3 rows and 4 columns
print(np.ndim(cost_price))
print(np.ndim(daily_sales))

(4,)
(3, 4)
1
2


manager decides to add 2 bonus units to  every product of products daily sale for a report. add 2 to entire daily sales array and then calculate total revenue. then multiply the cost_price array by the daily_sales matrix. Observe how numpy handles the multiplication of 1d and 2d array.

In [12]:
daily_sales_bonus = daily_sales + 2

print("\nAfter Adding Bonus Units:\n", daily_sales_bonus)

cost_price = np.array([2000, 50000, 8000])  # per unit

print("\nCost Price:\n", cost_price)

revenue_matrix = daily_sales_bonus * cost_price[:, np.newaxis]

print("\nRevenue Matrix:\n", revenue_matrix)

total_revenue = np.sum(revenue_matrix)

print("\nTotal Revenue =", total_revenue)


After Adding Bonus Units:
 [[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]

Cost Price:
 [ 2000 50000  8000]

Revenue Matrix:
 [[ 24000  34000  20000  28000]
 [350000 450000 300000 400000]
 [ 32000  40000  32000  48000]]

Total Revenue = 1758000


access sales data for smart watches for 4 days and for all products for first two daily_sales and
 for speakers on thursday using double indexing and 
using slicing subtract a 2 x 2 sub array representing sales of headphones and smartwatches for monday and tuesday.

In [ ]:
print(daily_sales[1]) #prints the second row of the daily_sales array which are 5, 7, 4, and 6

# 2 All products first two days
print(daily_sales[:, :2]) #prints all rows and first two columns of the daily_sales array which are 10, 15, 5, 7, 2, and 3

# 3 Speakers Thursday
print(daily_sales[2, 3])

# 4 Subtract 2x2 block
sub_array = daily_sales[0:2, 0:2] 
daily_sales[0:2, 0:2] -= sub_array


[0 0 4 6]
[[0 0]
 [0 0]
 [2 3]]
4


flatten the 3X4 daily_sales array into  1D aray of 12 elements using .reshape() 
convert the sales into a 2x6 matrix
use np.linespace() to create an array of 10 equal intervals betweeen 0 and 100 to represent "Discount Percentages".

In [6]:
flat_array = daily_sales.reshape(12)
print("Flattened array:\n", flat_array)

sales = daily_sales.reshape(2,6)
print("\n2x6 Matrix:\n", sales)


Flattened array:
 [ 0  0  8 12  0  0  4  6  2  3  2  4]

2x6 Matrix:
 [[ 0  0  8 12  0  0]
 [ 4  6  2  3  2  4]]


use np.random.randint to generate a new 3x4 array of "Predicted Sales" for the next week with values ranging from 0 to 20 
generate a random array of 5 numbers between 0 to 1 using np.random.rand
use np.sum() to find total sold items over 4 days and items sold for each product(Sum across rows)

In [7]:
predicted_sales = np.random.randint(0,21,(3,4))
print(predicted_sales)

random_values = np.random.rand(5)
print(random_values)

print("Total:", np.sum(daily_sales))

print("Per Product:", np.sum(daily_sales, axis=1))


[[ 9 16 14 18]
 [ 9  4 18 19]
 [ 4 19  4 20]]
[0.66508711 0.14397626 0.49938782 0.53459203 0.90990215]
Total: 41
Per Product: [20 10 11]
