In [2]:
import numpy as np


university monitors electricity usage
rows are hostels which are 4(H1,H2,H3,H4)
columns are days mon to sun 7 days
array name is electricity   

In [3]:
#task1: create an array of random integers between 120 and 650 with a shape of (4,7)
electricity = np.array([np.random.randint(120,650,(4,7))]) #
print(electricity)

print(electricity.shape)
print(electricity.ndim)
print(electricity.size)
print(electricity.dtype)  

[[[375 269 370 604 300 468 511]
  [346 387 628 478 140 591 556]
  [172 598 399 342 609 161 190]
  [270 437 645 587 634 427 600]]]
(1, 4, 7)
3
28
int32


In [4]:
#calculate the average electricity consumption of each hostel
avg_electricity_per_hostel = np.mean(electricity[:], axis=1) #perform mean along the rows

print(avg_electricity_per_hostel) #print avg electricity of each hostel

print(max(avg_electricity_per_hostel))
max_electricity = np.where(avg_electricity_per_hostel == max(avg_electricity_per_hostel),1,0)
print(max_electricity)

electricity_consumption_everyday = np.mean(electricity[0], axis=0)
print(electricity_consumption_everyday)





[[290.75 422.75 510.5  502.75 420.75 411.75 464.25]]
[290.75 422.75 510.5  502.75 420.75 411.75 464.25]
[[1 1 1 1 1 1 1]]
[290.75 422.75 510.5  502.75 420.75 411.75 464.25]


In [5]:
#if electricity_consumption_everyday[0] > 550 then surcharge of 20% is applied
surcharge = np.where(electricity_consumption_everyday > 550, electricity_consumption_everyday * 0.2, 0)
print(surcharge)

arr = electricity.copy()
print(arr)

penalty_array =np.where(arr > 550, arr * 1.2,arr)
print(penalty_array)

check = np.where(penalty_array == arr, 0,1)
print(check)

[0. 0. 0. 0. 0. 0. 0.]
[[[375 269 370 604 300 468 511]
  [346 387 628 478 140 591 556]
  [172 598 399 342 609 161 190]
  [270 437 645 587 634 427 600]]]
[[[375.  269.  370.  724.8 300.  468.  511. ]
  [346.  387.  753.6 478.  140.  709.2 667.2]
  [172.  717.6 399.  342.  730.8 161.  190. ]
  [270.  437.  774.  704.4 760.8 427.  720. ]]]
[[[0 0 0 1 0 0 0]
  [0 0 1 0 0 1 1]
  [0 1 0 0 1 0 0]
  [0 0 1 1 1 0 1]]]


In [6]:
daily_avg = np.where(electricity > avg_electricity_per_hostel,"True","False")
print(daily_avg)

[[['True' 'False' 'False' 'True' 'False' 'True' 'True']
  ['True' 'False' 'True' 'False' 'False' 'True' 'True']
  ['False' 'True' 'False' 'False' 'True' 'False' 'False']
  ['False' 'True' 'True' 'True' 'True' 'True' 'True']]]


In [7]:
#reshape the electricty data into single row representing weekly usage(shape 1*28)
weekly_usage = electricity.reshape(1,28)
print(weekly_usage)

#reshape the electricty data into 2 rows and 14 columns representing. no data is lost or dupliacted
reshaped_electricity = electricity.reshape(2,14)
print(reshaped_electricity)

[[375 269 370 604 300 468 511 346 387 628 478 140 591 556 172 598 399 342
  609 161 190 270 437 645 587 634 427 600]]
[[375 269 370 604 300 468 511 346 387 628 478 140 591 556]
 [172 598 399 342 609 161 190 270 437 645 587 634 427 600]]


In [8]:
#creaate a ref backup = electricty
#create a safe backup = electricty.copy()
#modify one value of origiinal
# observe which backup changes
backup = electricity
safe_backup = electricity.copy()

electricity = electricity + 10


#print(backup)
#print(safe_backup)
#print(electricity)
# conclusion is 

In [12]:
np.zeros(3)   # creates 1D array
np.zeros((2,3))  # 2 rows, 3 columns


array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.arange(5)         # start=0 default



array([0, 1, 2, 3, 4])

In [14]:

np.ones((3,3))

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])